### ISSUE TITLE
EMET no longer available from Microsoft

### ISSUE THREAD

**Issue by kvvloten** [juju4/ansible-harden-windows#2]
EMET has been phased out by MS and meanwhile the download link return a 404

https://download.microsoft.com/download/F/3/6/F366901C-F3CB-4A94-B377-5611740B8B19/EMET%20Setup.msi

This is the link used by the chocolatey package (which still exists but fails installing with 404)

What to do?

**Comment by juju4** [comment]
I will likely remove it from role as no more support and most functionalities are in win10 and above.

**Comment by juju4** [comment]
Done per https://github.com/juju4/ansible-harden-windows/commit/bde6de3b5ad3019f76254aeeb67d92b51b9a2faa
