### ISSUE TITLE
dc-krgtbt-reset.yml relies on technet (now deprecated)

### ISSUE THREAD

**Issue by TheBlackMini** [juju4/ansible-harden-windows#3]
I stumbled upon your repo and whilst browsing I found that one of your tasks relies on TechNet which no longer exists.
The New-KrbtgtKeys.ps1 script you're trying to download doesn't exist.

New location is https://github.com/microsoft/New-KrbtgtKeys.ps1/blob/master/New-KrbtgtKeys.ps1

**Comment by juju4** [comment]
Thanks for report and sorry for delay.
partial fixed was pushed on https://github.com/juju4/ansible-harden-windows/commit/96a2db0da2732b5d04a18b06c2828f24b7c28b92 but needs testing.

Won't be able to test in CI (which is currently broken anyway) as it would need a live domain.

**Comment by juju4** [comment]
Closing old issue and addressed normally
